
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sat May 28 23:47:03 CST 2022
//----------------------------------------------------

package codigoAnalizador;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Op_relacional = 24;
  public static final int Llave_cierre = 30;
  public static final int Llave_apertura = 29;
  public static final int Op_aritmetico = 20;
  public static final int Op_booleano = 27;
  public static final int Exponente = 23;
  public static final int Literal = 19;
  public static final int If = 4;
  public static final int Default = 18;
  public static final int Set = 10;
  public static final int Puts = 11;
  public static final int Else = 5;
  public static final int Break = 15;
  public static final int Then = 7;
  public static final int Diagonal_invertida = 22;
  public static final int Return = 14;
  public static final int While = 8;
  public static final int Op_relacional_cadena = 26;
  public static final int For = 9;
  public static final int Corchete_cierre = 32;
  public static final int Corchete_apertura = 31;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int Switch = 17;
  public static final int Linea = 2;
  public static final int ERROR = 36;
  public static final int ElseIf = 6;
  public static final int Continue = 16;
  public static final int Op_logico = 28;
  public static final int Expr = 12;
  public static final int Signo_dolar = 33;
  public static final int Identificador = 34;
  public static final int Procedimiento = 13;
  public static final int Op_incremento = 25;
  public static final int Numero = 35;
  public static final int Signo_interrogacion = 21;
  public static final int Comillas = 3;
}

